### ISSUE TITLE
ambiguous votes on aberration reference annotations 

### ISSUE THREAD

**Issue by johndashen** [raphael-group/magi#17]
On the main view page (in public MAGI) we can vote on a single reference within an annotation cell.  However, that reference may support multiple protein sequence changes; there is currently no way to specify which change is referred.  We might need to change how we design the interface for aberration annotation votes at this point to resolve it.

As an example: the tooltip, after voting:

![tooltip](https://cloud.githubusercontent.com/assets/7217604/9028938/9ec62170-3957-11e5-9d1a-7b14386df5e8.PNG)

The annotations table.
![table](https://cloud.githubusercontent.com/assets/7217604/9028939/9ec6e52e-3957-11e5-9155-2787583f8dd1.PNG)

**Comment by braphael8** [comment]
Hi John,
This is a good point.  We should redesign the interface on the aberration
view to only allow voting on "generic" annotations that are for the
particular cancer type rather than specific annotations for protein coding
changes.

Ben

**Comment by johndashen** [comment]
Hi Ben,
OK, just to be clear then - other annotations should be seen on this tooltip but not allowed to be voted on?
John
